/**:
  ros__parameters:
    width: 1280
    height: 720
    exposure: 1200
    auto_exposure: false
    gain: 9
    fps: 100
    auto_white_balace: false
    rgain: 19.8
    bgain: 19.8
    ggain: 10.0
    time_offset: 0
    offsetX: 0  # TODO
    offsetY: 0  # TODO

    rune_exposure: 600
    rune_gain: 12
    recording: false    #是否录制 TODO

    auto_exp_change: false
    max_exp: 3000
    min_exp: 200