/**:
  ros__parameters:
    use_video: true
    video_path: "/home/lzy/Videos/buff.mp4"
    images_floder_path: "/home/lzy/Pictures/rune_imgs/"

    width: 1280
    height: 1080
    exposure: 1200
    auto_exposure: false
    gain: 9
    fps: 185
    auto_white_balace: false
    rgain: 19.8
    bgain: 19.8
    ggain: 10.0
    time_offset: 45500000
    offsetX: 0  # TODO
    offsetY: 0  # TODO

    rune_exposure: 400
    rune_gain: 12
    recording: false    #是否录制 TODO

    auto_exp_change: false
    max_exp: 3000
    min_exp: 200