/**:
  ros__parameters:
    debug: 1

    # 相机到IMU存在位置的偏移
    camera2imu_offset_x: 0.065
    camera2imu_offset_y: 0.0
    camera2imu_offset_z: 0.0

    image_process_params:
      bin_threshold: 90.0
      enemy_color: 1 # 1--blue 0--red

    light_params:
      angle_to_vertical_max: 35.0
      height_width_min_ratio: 1.3
      size_area_min_ratio: 0.4

    armor_params:
      lights_angle_max_diff: 10.0
      lights_length_max_ratio: 1.5
      lights_Y_max_ratio: 1.5
      width_height_min_ratio: 1.1
      width_height_max_ratio: 6.5
      max_angle: 35.0
      inside_thresh: 85.0
