/**:
  ros__parameters:
    debug: 1
    control_interval: 10 # 控制间隔--ms

    lost_time_thres: 0.5
    # ekf params
    s2qxyz: 1.0
    s2qyaw: 0.5
    s2qr: 0.2

    r_xyz_factor: 2.8e-3
    r_yaw: 3e-4

    delay: 0.03
    true_x: 640

    gun_pitch_offset: -1.2
    gun_yaw_offset: 0.2
    rune_gun_pitch_offset: 0.0
    rune_gun_yaw_offset: 0.0

    bs_fly_time: 1.5
    ready_time: 0.5

    bs_coeff_first: 1.0
    bs_coeff_second: 1.0
    bs_coeff_third: 1.0
    bs_coeff_fourth: 1.0

    distance_first: 0
    distance_second: 3000
    distance_third: 0

    k: 0.0402
    g: 9.75
    bullet_speed: 28

    # tracker params
    max_match_distance: 0.5
    max_match_yaw_diff: 0.75
    tracking_thres: 10
    lost_thres: 60