/**:
  ros__parameters:
    image_params:
      show_R: 0
      blue_brightness_thresh: 30
      blue_color_thresh: 50
      red_brightness_thresh: 30
      red_color_thresh: 50
      blue_red_diff: 20


    deep_learning_params:
      circle_center_conf: 0
      no_activate_conf: 0.7
      activate_conf: 0
      circle_center_roi_width: 20
      max_diff_distance_ratio: 0.5

    fitting_params:
      points_num: 50
      delay_time: 0.0
      save_txt: 0
      print_result: 1
