/**:
  ros__parameters:
    rune_gun_pitch_offset: -1.8
    rune_gun_yaw_offset: 0.2 

    bs_fly_time: 580.0     
    ready_time: 150.0
    bullet_speed: 27



    level_first: 1.22
    level_second: 1.19  # 0.8
    level_third: 1.13   # 0.8
    level_fourth: 1.13  # 0.8

    height_first: 400
    height_second: 900
    height_third: 1200
    # height_fourth: 100
    k: 0.0402
    g: 9.75