/**:
  ros__parameters:
    rune_gun_pitch_offset: -0.8
    rune_gun_yaw_offset: 0.2

    bs_fly_time: 1380.0     
    ready_time: 0.0
    bullet_speed: 27


    debug: 1
    level_first: 1.28
    level_second: 1.24  # 0.8
    level_third: 1.18   # 0.8
    level_fourth: 1.28  # 0.8

    height_first: 800
    height_second: 1000
    height_third: 1200
    # height_fourth: 100b
    k: 0.0402
    g: 9.75