/**:
  ros__parameters:
    rune_gun_pitch_offset: -8.0
    rune_gun_yaw_offset: 7.8

    bs_fly_time: 1280.0     
    ready_time: 0.0
    bullet_speed: 27


    debug: 1
    level_first: 1.24
    level_second: 1.24  # 0.8
    level_third: 1.28   # 0.8
    level_fourth: 1.3  # 0.8

    height_first: -150
    height_second: 100
    height_third: 900
    # height_fourth: 100
    k: 0.0402
    g: 9.75